In [846]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [847]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
print(test['MSZoning'].unique())

['RH' 'RL' 'RM' 'FV' 'C (all)' nan]


In [848]:
train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [849]:
print(test['MSZoning'].unique())

['RH' 'RL' 'RM' 'FV' 'C (all)' nan]


In [850]:
train.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [851]:
train.columns


Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [852]:
train.drop([ 'Alley','LandContour','LotConfig','Condition1', 'Condition2','HouseStyle', 'RoofMatl','Exterior1st','MasVnrType','BsmtExposure','BsmtFinType2', 'BsmtFinSF2','Functional'],inplace=True,axis=1)

In [853]:
test.drop([ 'Alley','LandContour','LotConfig','Condition1', 'Condition2','HouseStyle', 'RoofMatl','Exterior1st','MasVnrType','BsmtExposure','BsmtFinType2', 'BsmtFinSF2','Functional'],inplace=True,axis=1)

In [854]:
train.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 68 columns]

In [855]:
per=(train.isnull().sum()/len(train))*100

In [856]:
per.sort_values(ascending=True)

Id                0.000000
2ndFlrSF          0.000000
SaleCondition     0.000000
GrLivArea         0.000000
BsmtFullBath      0.000000
                   ...    
LotFrontage      17.739726
FireplaceQu      47.260274
Fence            80.753425
MiscFeature      96.301370
PoolQC           99.520548
Length: 68, dtype: float64

In [857]:
train.drop(['PoolQC','MiscFeature','Fence'],axis=1,inplace=True)

In [858]:
test.drop(['PoolQC','MiscFeature','Fence'],axis=1,inplace=True)

In [859]:
train.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 65 columns]

In [860]:
train['MSSubClass'].unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  85,  80, 160,  75,
       180,  40])

In [861]:
train['LotFrontage'].unique()

array([ 65.,  80.,  68.,  60.,  84.,  85.,  75.,  nan,  51.,  50.,  70.,
        91.,  72.,  66., 101.,  57.,  44., 110.,  98.,  47., 108., 112.,
        74., 115.,  61.,  48.,  33.,  52., 100.,  24.,  89.,  63.,  76.,
        81.,  95.,  69.,  21.,  32.,  78., 121., 122.,  40., 105.,  73.,
        77.,  64.,  94.,  34.,  90.,  55.,  88.,  82.,  71., 120., 107.,
        92., 134.,  62.,  86., 141.,  97.,  54.,  41.,  79., 174.,  99.,
        67.,  83.,  43., 103.,  93.,  30., 129., 140.,  35.,  37., 118.,
        87., 116., 150., 111.,  49.,  96.,  59.,  36.,  56., 102.,  58.,
        38., 109., 130.,  53., 137.,  45., 106., 104.,  42.,  39., 144.,
       114., 128., 149., 313., 168., 182., 138., 160., 152., 124., 153.,
        46.])

In [862]:
train['LotFrontage']=train['LotFrontage'].fillna(train['LotFrontage'].mean())

In [863]:
train['MasVnrArea'].unique()

array([1.960e+02, 0.000e+00, 1.620e+02, 3.500e+02, 1.860e+02, 2.400e+02,
       2.860e+02, 3.060e+02, 2.120e+02, 1.800e+02, 3.800e+02, 2.810e+02,
       6.400e+02, 2.000e+02, 2.460e+02, 1.320e+02, 6.500e+02, 1.010e+02,
       4.120e+02, 2.720e+02, 4.560e+02, 1.031e+03, 1.780e+02, 5.730e+02,
       3.440e+02, 2.870e+02, 1.670e+02, 1.115e+03, 4.000e+01, 1.040e+02,
       5.760e+02, 4.430e+02, 4.680e+02, 6.600e+01, 2.200e+01, 2.840e+02,
       7.600e+01, 2.030e+02, 6.800e+01, 1.830e+02, 4.800e+01, 2.800e+01,
       3.360e+02, 6.000e+02, 7.680e+02, 4.800e+02, 2.200e+02, 1.840e+02,
       1.129e+03, 1.160e+02, 1.350e+02, 2.660e+02, 8.500e+01, 3.090e+02,
       1.360e+02, 2.880e+02, 7.000e+01, 3.200e+02, 5.000e+01, 1.200e+02,
       4.360e+02, 2.520e+02, 8.400e+01, 6.640e+02, 2.260e+02, 3.000e+02,
       6.530e+02, 1.120e+02, 4.910e+02, 2.680e+02, 7.480e+02, 9.800e+01,
       2.750e+02, 1.380e+02, 2.050e+02, 2.620e+02, 1.280e+02, 2.600e+02,
       1.530e+02, 6.400e+01, 3.120e+02, 1.600e+01, 

In [864]:
train['MasVnrArea']=train['MasVnrArea'].fillna(train['MasVnrArea'].mean())

In [865]:
train['BsmtQual'].unique()

array(['Gd', 'TA', 'Ex', nan, 'Fa'], dtype=object)

In [866]:
train['BsmtQual']=train['BsmtQual'].fillna('None')

In [867]:
train['BsmtCond']=train['BsmtCond'].fillna('None')

In [868]:
train['BsmtFinType1']=train['BsmtFinType1'].fillna('None')

In [869]:
train['Electrical']=train['Electrical'].fillna('None')

In [870]:
train['FireplaceQu']=train['FireplaceQu'].fillna('None')

In [871]:
train['GarageType']=train['GarageType'].fillna('None')

In [872]:
train['GarageYrBlt']=train['GarageYrBlt'].fillna(train['GarageYrBlt'].median())

In [873]:
train['GarageFinish']=train['GarageFinish'].fillna('None')

In [874]:
train['GarageQual']=train['GarageQual'].fillna('None')

In [875]:
train['GarageCond']=train['GarageCond'].fillna('None')

In [876]:
simplified=train.isnull().sum()/len(train)*100
simplified.sort_values(ascending=True)

Id              0.0
GrLivArea       0.0
BsmtFullBath    0.0
BsmtHalfBath    0.0
FullBath        0.0
               ... 
Heating         0.0
HeatingQC       0.0
CentralAir      0.0
1stFlrSF        0.0
SalePrice       0.0
Length: 65, dtype: float64

In [877]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()


In [878]:
for i in train:
    if train[i].dtypes==object:
      train[i]=lc.fit_transform(train[i])
    else:
      pass

In [879]:
train['Neighborhood'].unique()

array([ 5, 24,  6, 15, 11, 21, 14, 17,  3, 19, 16, 12, 20,  9, 10,  7, 23,
        8, 22,  4, 13,  0,  2, 18,  1])

In [880]:
ytrain=train['SalePrice']

In [881]:
test_id=test['Id']

In [882]:
train.drop(['SalePrice','Id'],inplace=True,axis=1)

In [883]:
test.drop(['Id'],inplace=True,axis=1)

In [884]:
xtrain=train

In [885]:
xtrain

MSSubClass  MSZoning  LotFrontage  ...  YrSold  SaleType  SaleCondition
0             60         3         65.0  ...    2008         8              4
1             20         3         80.0  ...    2007         8              4
2             60         3         68.0  ...    2008         8              4
3             70         3         60.0  ...    2006         8              0
4             60         3         84.0  ...    2008         8              4
...          ...       ...          ...  ...     ...       ...            ...
1455          60         3         62.0  ...    2007         8              4
1456          20         3         85.0  ...    2010         8              4
1457          70         3         66.0  ...    2010         8              4
1458          20         3         68.0  ...    2010         8              4
1459          20         3         75.0  ...    2008         8              4

[1460 rows x 63 columns]

In [886]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators=100,random_state=0)
rfr.fit(xtrain,ytrain)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [887]:
len(xtrain.columns)

63

In [888]:
len(test.columns)

63

In [889]:
for i in test:
  if test[i].isnull().sum()!=0 :
    if test[i].dtypes==object :
      test[i]=test[i].fillna('None')
    else:
      test[i]=test[i].fillna(test[i].mean())

In [890]:
for i in test:
    if test[i].dtypes==object:
      test[i]=lc.fit_transform(test[i])
    else:
      pass

In [891]:
pred=rfr.predict(test)

**HOUSE PRICE PREDICTION OF THE TEST DATA**

In [897]:
output=pd.DataFrame({'Id':test_id,'Saleprice':pred})
output

Id  Saleprice
0     1461  123126.24
1     1462  155277.75
2     1463  169004.00
3     1464  174468.32
4     1465  199384.56
...    ...        ...
1454  2915   85431.11
1455  2916   85780.25
1456  2917  152285.25
1457  2918  110206.08
1458  2919  215911.07

[1459 rows x 2 columns]